### ISSUE TITLE
Issue installing fafbseg using natmanager

### ISSUE THREAD

**Issue by dempseyg447** [natverse/natmanager#15]
if (!requireNamespace("natmanager")) install.packages("natmanager")
> natmanager::install(pkgs="fafbseg")
Error: `github_token()` was deprecated in usethis 2.0.0 and is now defunct.
Call `gh::gh_token()` to retrieve a GitHub personal access token
Call `gh_token_help()` if you need help getting or configuring your token

I haven't changed anything and my GitHub PAT is located in my environ file

**Comment by SridharJagannathan** [comment]
Closed via https://github.com/natverse/natmanager/compare/bb2f0..66c5e

**Comment by jefferis** [comment]
Thanks @SridharJagannathan!

**Comment by jefferis** [comment]
PS @SridharJagannathan it would be great to bump the package version as then we can advise people to do: 

```
natmanager::selfupdate()
```

rather than using remotes.

**Comment by SridharJagannathan** [comment]
@jefferis I'm afraid that logic won't work, because the code will fail at:
https://github.com/natverse/natmanager/blob/eb51406d2058d4a375b75191a3cb69cf688f65d0/R/update.R#L28
which will result in error like below (because the `selfupdate` checks for `PAT` first, which can't be done with the updated `usethis` package).. 
```
Error: `github_token()` was deprecated in usethis 2.0.0 and is now defunct.
Call `gh::gh_token()` to retrieve a GitHub personal access token
Call `gh_token_help()` if you need help getting or configuring your token

```

For the time being, I have bumped up the version to `0.4.7` and modified install instructions to get stuff from `GitHub` until we have a new version up on `CRAN`
