### ISSUE TITLE
Test cases related to install fail in travis with older r versions (<4.0)

### ISSUE THREAD

**Issue by SridharJagannathan** [natverse/natmanager#17]
To reproduce this issue, uncomments the following line, and bump to travis 
https://github.com/natverse/natmanager/blob/eb51406d2058d4a375b75191a3cb69cf688f65d0/.travis.yml#L4

This will result in an error in travis, see below for an example:
https://travis-ci.org/github/natverse/natmanager/jobs/749700874
If you look further, you can see that this is because 
```
ERROR: dependency ‘rgl’ is not available for package ‘nat’
```

on further investigation, I found that [rgl](https://cran.r-project.org/web/packages/rgl/index.html) requires a minimum r version of 4.0.0.
It would be good to think about migrating to 4.0.0 in the upcoming releases.

**Comment by jefferis** [comment]
Thanks @SridharJagannathan. Very surprising change in rgl. Note that there is no requirement for natmanager itself to have an R 4.0 dependency even with this decision to make rgl depend on R>4.0. rgl is not a dependency of natmanager.

**Comment by jefferis** [comment]
Hi @SridharJagannathan, further to this, I have corresponded with Duncan Murdoch, the author of rgl, and he was extremely helpful and responsive. He was able to roll back the dependency requirement to R 3.2.0. Although it will take a while for this to make it to CRAN given their Christmas holiday, the updated version is already available from [r-forge](https://r-forge.r-project.org/R/?group_id=234) but since binaries from rforge are only available for the latest version of R, they will not really help anyone yet.

**Comment by SridharJagannathan** [comment]
Closing, as the minimum recommended R version now is `4.0.2`
https://github.com/natverse/natmanager/blob/master/R/utils.R#L27
