### ISSUE TITLE
selfupdate doesn't recognise new version

### ISSUE THREAD

**Issue by SridharJagannathan** [natverse/natmanager#3]
The scenario is as follows:
1) In your local version of `natmanager` change the version number in the `DESCRIPTION` file to say something like `Version: 0.2.9`
2) Now run the `selfupdate` function after using load all in `r-studio`
3) This will force a new install of the `natmanager` which is currently at `Version: 0.3.0`
4) Now here: https://github.com/natverse/natmanager/blob/master/R/update.R#L33 it should return the new version as 0.3.0 and should force a restart of the `r `
5) However it doesn't do that because the `newVersion=utils::packageVersion('natmanager')` still retains the old version (as the version numbers are taken from the attached environment which hasn't changed).
The logic should be changed in such a way that the newversion is taken after install directly from `GitHub` or `CRAN` and not dependent on the attached environment.

**Comment by SridharJagannathan** [comment]
Furthermore we should also may be consider using the `SHA1` version for `GitHub` instead of the version numbers as it is not necessary that we would update version numbers for every incremental change made.

**Comment by jefferis** [comment]
* In step 2 you need to "Build and Reload" (from a different session) not "Load All" otherwise the version 0.2.9 package is not installed. If packageVersion() still returns 0.3.0 after you do that, then there is a problem, but AFAICS it reads from the install location on disk every time.

> Furthermore we should also may be consider using the SHA1 version for GitHub instead of the version numbers as it is not necessary that we would update version numbers for every incremental change made.
I considered and rejected this option because I wanted to be able to compare CRAN and GitHub versions and there is no easy way to establish the github SHA1 for the CRAN version. *It does mean that every update pushed to GitHub must have a version bump*

**Comment by SridharJagannathan** [comment]
> 2. Now run the `selfupdate` function after using load all in `r-studio`

@jefferis As you pointed out, Indeed the problem seems to be with load all, when I tired this in a separate session (after installing lower version in another session) it seemed to install the latest version and did restart as well!
